### ISSUE TITLE
Integrate Slack and this repo

### ISSUE THREAD

**Issue by joshuabailes** [18F/agreements-public#10]
@adelevie can you help me figure out how to post issues from this repo automatically in the slack channel #iaa-transparency

Thanks!

**Comment by afeld** [comment]
Done! Let us know in #admins-slack if you want any of the settings changed.

![screen shot 2016-02-05 at 3 18 04 pm](https://cloud.githubusercontent.com/assets/86842/12858059/b85c409a-cc1b-11e5-858d-283b3ad74977.png)
