### ISSUE TITLE
Agreements to Load

### ISSUE THREAD

**Issue by joshuabailes** [18F/agreements-public#9]
The full spectrum of OCSIT MOUs is ready to load. I just need someone to load them. Note that some do not have a MB number at this time. We are awaiting that number from our finance department in Kansas City. We can post with the temporary number and I can update or create a new issue when those numbers are updated.

All but one are readable text files.

Also updated the sheet to better track things. basically, column N is the approval to post column. look for **yes** there. The files are linked in column O, and in some cases a second file in P where there was a modification to that agreement.

https://docs.google.com/spreadsheets/d/1qqDxh9Jhy4Y-_Qhgnimrja8i6KnztxPviyqRhz_NeyU/edit#gid=448576162

@adelevie @stvnrlly

**Comment by stvnrlly** [comment]
This is ongoing in #11.
